### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by nagimov** [nagimov/cyclotron-cryopanel#29]
After the replacement of `props_...` function with c-like code, huge memory consumption is observed.
One run of the script (~few thousand function calls) consumes few GBs of RAM.
To be investigated

**Comment by nagimov** [comment]
@savreline lets try to reload (unload and load back) coolprop library every now and then (say every 10th timestep or something like that). Do not do that every iteration, since that's a bit expensive.
So we now have `loadlibrary(libname,'CoolPropLib.h','includepath',path_to_include,'alias','coolprop');` loading the lib, to unload it just call `unloadlibrary libname`

**Comment by nagimov** [comment]
it should be `unloadlibrary 'coolprop'`, just checked

**Comment by savreline** [comment]
@nagimov Nine saw-tooth now. I have a variable `CP_dump = 10` in the code that we can adjust how often we wish to dump the library. I will set it to 20 right now, since I would like to dump only once during the iteration to save time. If you run the code on your computer, you can set that variable to 5 if you wish. 

![image](https://cloud.githubusercontent.com/assets/21995425/19395676/b52ede8e-91f3-11e6-82c2-21a9224ba9f3.png)

**Comment by nagimov** [comment]
solved, closing
